parameters:
  - name: 'jobName'
    type: string
  - name: 'containerRegistry' #service connection name
    type: string
  - name: 'repository' #dockerhub repository name
    type: string
  - name: 'imageTag'
    type: string 
  - name: 'dockerPath' #docker file path
    type: string

jobs:
  - job:
    displayName: ${{ parameters.jobName }}
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: '${{ parameters.containerRegistry }}'
          repository: '${{ parameters.repository }}'
          command: 'buildAndPush'
          Dockerfile: '${{ parameters.dockerPath }}'
          tags: '${{ parameters.imageTag }}'
          buildContext: $(Pipeline.Workspace)
        displayName: Docker build and push
